### ISSUE TITLE
Name of executable is confusing

### ISSUE THREAD

**Issue by bestlem** [ToyVo/nh#6]
As the nh here is a fork of the original and does some extra things I think it might be useful to rename the executable as say nh-darwin as it will not be merged into the original.

As an example of issues see https://github.com/LnL7/nix-darwin/pull/942

**Comment by ToyVo** [comment]
I wasn't nessisarily wanting to rename to nh-darwin for 2 reasons. 
- Nixos is still supposed.
- I don't want to type nh-darwin. 

This can be side stepped by adding an alias to nh though.

I have also been mulling over nih or some other 3 letter name but it's whatever honestly

**Comment by ToyVo** [comment]
I have now renamed to nh-darwin. I have not added a module option to add an alias, you'll have to do that yourself. Additionally the default darwin module is now designed for after the nix-darwin PR is merged, for before hand if you want my version of the module you can use prebuiltin module instead of the default one
